routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(array('middleware' => 'auth'),function(){
	Route::post('users/delete', 'UserController@delete')->name('users.delete');
	Route::post('/users/update/{id}', 'UserController@update')->name('users.update');
	Route::resource('/users', 'UserController',['except'=>['update','delete']]);

	Route::get('/blog', 'BlogController@index')->name('blog.index');

});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{

    protected $table = 'blogs';
    protected $fillable = ['id', 'title','slug','description','user_id']; 
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable,SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'user_name','email','password','gender','contact_no','dob'
    ];
    protected $dates = ['deleted_at'];
    protected $softDelete = true;
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Blog(){
        return $this->hasMany('App\Blog','user_id','id');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;

class BlogController extends Controller
{
    public function index(){
    	$blogs = User::with('Blog')->where('id',Auth::id())->get()->toArray();

    	return view('blogs.index',compact('blogs'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Blog;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_count =  User::where('deleted_at',NULL)->count();
        $blog_count =  Blog::where('user_id',\Auth::id())->count();

        return view('home',compact('user_count','blog_count'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UsersRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Blog;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $relationship = User::with('Blog')->get()->toArray();
        // dd($relationship);
        $users = User::get()->toArray();
        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name'        => 'required|alpha|max:32',

            'last_name'         => 'required|alpha|max:32',
            'username'         => 'required|alpha|max:32',
            'password'          => 'required|min:6',
            'confirm_password'  => 'required|same:password', 

            'contact_no'        => 'required|numeric|digits_between:6,18|regex:/^[0-9]{1,10}$/',

            'email'             => 'required|email|max:100|unique:users,email,NULL,id,deleted_at,NULL',
            'gender'            => 'required',
        ]);
        $user_data = $request->all();
        $user = new User();
        $user->first_name = $user_data['first_name'];
        $user->last_name = $user_data['last_name'];
        $user->username = $user_data['username'];
        $user->password = \Hash::make($user_data['password']);
        $user->contact_no = $user_data['contact_no'];
        $user->email = $user_data['email'];
        $user->gender = $user_data['gender'];
        $user->dob = date('Y-m-d',strtotime($user_data['dob']));
        $user->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function show(user $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(user $user)
    {
        $user['dob'] = date('d-m-Y',strtotime($user['dob']));
        return view('users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, user $user)
    {
        $id = \Request::segment(3);                                                                             
        $this->validate($request, [
            'first_name'        => 'required|alpha|max:32',

            'last_name'         => 'required|alpha|max:32',
            'username'         => 'required|alpha|max:32',

            'contact_no'        => 'required|numeric|digits_between:6,18|regex:/^[0-9]{1,10}$/',

            'email' => 'required|email|max:100|unique:users,email,{$id},id,deleted_at,NULL',
            'gender'            => 'required',
        ]);
        $user_data = $request->all();
        $user = User::find(\Request::segment(3));
        $user->first_name = $user_data['first_name'];
        $user->last_name = $user_data['last_name'];
        $user->username = $user_data['username'];
        $user->contact_no = $user_data['contact_no'];
        $user->email = $user_data['email'];
        $user->gender = $user_data['gender'];
        $user->dob = date('Y-m-d',strtotime($user_data['dob']));
        $user->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
        $user_data  = $request->all();


        if($user_data['id'] == \Auth::id()){
            return "error";
        }else{
            $user_delete = User::find($user_data['id'])->delete();
            return "success";
        }
    }
}

resources/views/blogs/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Practical Test</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Blogs List
    <a href="{{route('home')}}" class="btn btn-info btn-lg" style="font-size: 12px;font-weight: bold;float: right;margin-bottom: 10px;margin-right: 10px" >
      <span class="glyphicon glyphicon-arrow-left"></span> Back 
    </a>
  </h2>   
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Slug</th>
      </tr>
    </thead>
    <tbody>
      @if(count($blogs[0]['blog']) > 0)
        @foreach($blogs[0]['blog'] as $value)
          <tr>
            <td>{{$value['title']}}</td>
            <td>{{$value['description']}}</td>
            <td>{{$value['slug']}}</td>
          </tr>
        @endforeach
      @else
        <tr><td>There were no record found!</td></tr>  
      @endif
    </tbody>
  </table>
</div>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="container bootstrap snippet">
                        <div class="row">
                            <a href="{{route('users.index')}}">
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="mini-stat clearfix bg-facebook rounded">
                                        <span class="mini-stat-icon"><i class="fa fa-user"></i></span>
                                        <div class="mini-stat-info">
                                            <span>{{$user_count}}</span>
                                            Users
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <a href="{{route('blog.index')}}">
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="mini-stat clearfix bg-twitter rounded">
                                        <span class="mini-stat-icon"><i class="fa fa-user"></i></span>
                                        <div class="mini-stat-info">
                                            <span>{{$blog_count}}</span>
                                            Blog
                                        </div>
                                    </div>
                                </div>  
                            </a>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{asset('css/dashboard.css')}}">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @if(Auth::check())
                        <a class="navbar-brand" href="{{ route('users.index') }}" style="    background: #00a0d1;color: white;font-weight: bold;">
                            User
                        </a>

                        <a class="navbar-brand" href="{{ route('blog.index') }}" style="    background: #00a0d1;color: white;font-weight: bold;margin-left: 10px">
                            Blog
                        </a>
                    @endif
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ ucfirst(Auth::user()->first_name) }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/users/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Practical Test</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{asset('css/dataranger.css')}}">
  <link rel="stylesheet" href="{{asset('css/daterangepicker.css')}}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="{{asset('js/daterangepicker.min.js')}}"></script>
  <script src="{{asset('js/moment.min.js')}}"></script>
  <script src="{{asset('js/dateranger.js')}}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Users Add
  <a href="{{route('users.index')}}" class="btn btn-info btn-lg" style="font-size: 12px;font-weight: bold;float: right;margin-bottom: 10px" >
      <span class="glyphicon glyphicon-arrow-left"></span> Back 
    </a>
  </h2>
  <form class="form-horizontal" action="{{route('users.store')}}" method="post" id="user_form">

    <div class="form-group" id="first_name_error_div">
      <label class="control-label col-sm-2" for="first_name">First Name:</label>
      <div class="col-sm-10">
        <input type="first_name" class="form-control" id="first_name" placeholder="Enter First Name" name="first_name">
        <span id="first_name_error"><?=$errors->first('first_name')?></span>
      </div>
    </div>
    <div class="form-group" id="last_name_error_div">
      <label class="control-label col-sm-2" for="last_name">Last Name:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="last_name" placeholder="Enter Last Name" name="last_name">
        <span id="last_name_error"><?=$errors->first('last_name')?></span>

      </div>
    </div>
    <div class="form-group" id="user_name_error_div">
      <label class="control-label col-sm-2" for="user_name">User Name:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="user_name" placeholder="Enter User Name" name="user_name">
        <span id="user_name_error"><?=$errors->first('user_name')?></span>

      </div>
    </div>
    <div class="form-group" id="email_error_div">
      <label class="control-label col-sm-2" for="email">Email:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="email" placeholder="Enter Email" name="email">
        <span id="email_error"><?=$errors->first('email')?></span>

      </div>
    </div>
    <div class="form-group" id="password_error_div">
      <label class="control-label col-sm-2" for="password">Password:</label>
      <div class="col-sm-10">          
        <input type="password" class="form-control" id="password" placeholder="Enter Password" name="password">
        <span id="password_error"><?=$errors->first('password')?></span>

      </div>
    </div>
    <div class="form-group" id="confirm_password_error_div">
      <label class="control-label col-sm-2" for="confirm_password">Confirm Password:</label>
      <div class="col-sm-10">          
        <input type="password" class="form-control" id="confirm_password" placeholder="Enter Confirm Password" name="confirm_password">
        <span id="confirm_password_error"><?=$errors->first('confirm_password')?></span>

      </div>
    </div>
    <div class="form-group" id="gender_error_div">
      <label class="control-label col-sm-2" for="gender">Gender:</label>
      <div class="col-sm-10">          
        <select class="form-control" name="gender">
          <option value="">Select Gender</option>
          @foreach(config('project.gender') as $value)
          <option value="{{$value}}">{{ucfirst($value)}}</option>
          @endforeach
        </select>
        <span id="gender_error"><?=$errors->first('gender')?></span>

      </div>
    </div>
    <div class="form-group" id="contact_no_error_div">
      <label class="control-label col-sm-2" for="contact_no">Contact Number:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="contact_no" placeholder="Enter Contact Number" name="contact_no">
        <span id="contact_no_error"><?=$errors->first('contact_no')?></span>

      </div>
    </div>
    <div class="form-group" id="dob_error_div">
      <label class="control-label col-sm-2" for="dob">Date Of Birth:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="dob" name="dob">
        <span id="dob_error"><?=$errors->first('dob')?></span>

      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  </form>
</div>

</body>
<script type="text/javascript">
  $('input[name="dob"]').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    "locale": {
        "format": "DD-MM-YYYY",
    },
    maxDate: new Date()
  });
  $("#user_form").on('submit', function (e) {
    e.preventDefault();
    var path = "<?=URL::route('users.store')?>";
    $.ajax({
        type: 'POST',
        url: path,
        data: new FormData($("#user_form")[0]),
        async:true,
        processData: false,
        contentType: false,
        success: function (data) 
        {
            toastr.success("User has been added successfully");
            setTimeout(function(){ 
              window.location.href = "{{route('users.index')}}" 
            }, 1000);
        },
        error: function (response) 
        {
          $("[id$='_error']").empty();
          $("[id$='_error_div']").removeClass('text-danger');

            $.each(response.responseJSON.errors, function(k,v){
              $('#'+k+'_error').text(v);
              $('#'+k+'_error_div').addClass('text-danger');

          });

        }
    })
});
</script>
  
</html>

resources/views/users/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Practical Test</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{asset('css/dataranger.css')}}">
  <link rel="stylesheet" href="{{asset('css/daterangepicker.css')}}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="{{asset('js/daterangepicker.min.js')}}"></script>
  <script src="{{asset('js/moment.min.js')}}"></script>
  <script src="{{asset('js/dateranger.js')}}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</head>
<body>

<div class="container">
  <h2>User Edit
    <a href="{{route('users.index')}}" class="btn btn-info btn-lg" style="font-size: 12px;font-weight: bold;float: right;margin-bottom: 10px" >
      <span class="glyphicon glyphicon-arrow-left"></span> Back 
    </a>
  </h2>
  <form class="form-horizontal" action="{{route('users.store')}}" method="post" id="user_form">
  <input type="hidden" name="id" value="{{$user['id']}}" id="id">
    <div class="form-group" id="first_name_error_div">
      <label class="control-label col-sm-2" for="first_name">First Name:</label>
      <div class="col-sm-10">
        <input type="first_name" class="form-control" id="first_name" placeholder="Enter First Name" name="first_name" value="{{$user['first_name']}}">
        <span id="first_name_error"><?=$errors->first('first_name')?></span>
      </div>
    </div>
    <div class="form-group" id="last_name_error_div">
      <label class="control-label col-sm-2" for="last_name">Last Name:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="last_name" placeholder="Enter Last Name" name="last_name" value="{{$user['last_name']}}">
        <span id="last_name_error"><?=$errors->first('last_name')?></span>

      </div>
    </div>
    <div class="form-group" id="user_name_error_div">
      <label class="control-label col-sm-2" for="user_name">User Name:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="user_name" placeholder="Enter User Name" name="user_name" value="{{$user['user_name']}}">
        <span id="user_name_error"><?=$errors->first('user_name')?></span>

      </div>
    </div>
    <div class="form-group" id="email_error_div">
      <label class="control-label col-sm-2" for="email">Email:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="email" placeholder="Enter Email" name="email" value="{{$user['email']}}">
        <span id="email_error"><?=$errors->first('email')?></span>

      </div>
    </div>
    <div class="form-group" id="gender_error_div">
      <label class="control-label col-sm-2" for="gender">Gender:</label>
      <div class="col-sm-10">          
        <select class="form-control" name="gender">
          <option value="">Select Gender</option>
          @foreach(config('project.gender') as $value)
          <option value="{{$value}}" @if($value == $user['gender']) selected="true" @endif>{{ucfirst($value)}}</option>
          @endforeach
        </select>  
        <span id="gender_error"><?=$errors->first('gender')?></span>

      </div>
    </div>
    <div class="form-group" id="contact_no_error_div">
      <label class="control-label col-sm-2" for="contact_no">Contact Number:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="contact_no" placeholder="Enter Contact Number" name="contact_no" value="{{$user['contact_no']}}">
        <span id="contact_no_error"><?=$errors->first('contact_no')?></span>

      </div>
    </div>
    <div class="form-group" id="dob_error_div">
      <label class="control-label col-sm-2" for="dob">Date Of Birth:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="dob" name="dob" value="{{$user['dob']}}">
        <span id="dob_error"><?=$errors->first('dob')?></span>

      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Update</button>
      </div>
    </div>
  </form>
</div>

</body>
<script type="text/javascript">
  $('input[name="dob"]').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    "locale": {
        "format": "DD-MM-YYYY",
    },
    maxDate: new Date()
  });
  $("#user_form").on('submit', function (e) {
    var id = $('#id').val();
    e.preventDefault();
    var url1 = "<?=URL::route('users.update', ['id' => ':id'])?>";
    var path = url1.replace(':id',id);
    $.ajax({
        type: 'POST',
        url: path,
        data: new FormData($("#user_form")[0]),
        async:true,
        processData: false,
        contentType: false,
        success: function (data) 
        {
            toastr.success("User has been updated successfully");
            setTimeout(function(){ 
              window.location.href = "{{route('users.index')}}" 
            }, 1000);
        },
        error: function (response) 
        {
          $("[id$='_error']").empty();
          $("[id$='_error_div']").removeClass('text-danger');

            $.each(response.responseJSON.errors, function(k,v){
              $('#'+k+'_error').text(v);
              $('#'+k+'_error_div').addClass('text-danger');

          });

        }
    })
});
</script>
  
</html>

resources/views/users/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Practical Test</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Users List
    <a href="{{route('users.create')}}" class="btn btn-info btn-lg" style="font-size: 12px;font-weight: bold;float: right;" >
      <span class="glyphicon glyphicon-plus"></span> Add 
    </a>
    <a href="{{route('home')}}" class="btn btn-info btn-lg" style="font-size: 12px;font-weight: bold;float: right;margin-bottom: 10px;margin-right: 10px" >
      <span class="glyphicon glyphicon-arrow-left"></span> Back 
    </a>
  </h2>   
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>User Name</th>
        <th>Email</th>
        <th>Contact Number</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach($users as $value)
        <tr>
          <td>{{$value['first_name']}}</td>
          <td>{{$value['last_name']}}</td>
          <td>{{$value['username']}}</td>
          <td>{{$value['email']}}</td>
          <td>{{$value['contact_no']}}</td>
          <td>
            <p>
              <a href="{{route('users.edit',$value['id'])}}" class="btn btn-info btn-lg" style="font-size: 12px;
    font-weight: bold;">
                <span class="glyphicon glyphicon-pencil"></span> Edit 
              </a>
              <a href="javascript:;" class="btn btn-info btn-lg delete" style="font-size: 12px;font-weight: bold;" data-id="{{$value['id']}}">
                <span class="glyphicon glyphicon-trash"></span> Delete 
              </a>
            </p> 
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
</div>
<script type="text/javascript">
  $('.delete').click(function(){
    console.log('hi');
    var result = confirm("Do you want to delete?");
    var id = $(this).attr('data-id');
    console.log(id);
    if (result) {
      $.ajax({
        type: 'POST',
        url: "{{route('users.delete')}}",
        data: {'id':id,'_token':"{{csrf_token()}}"},
        success: function (data) 
        {
            if(data == "success"){
              toastr.success("User has been deleted successfully");
            }else{
              toastr.error("Logged in User can not be delete");
            }
            setTimeout(function(){ 
              window.location.href = "{{route('users.index')}}" 
            }, 1000);
        },
      });
    }      
  })
</script>
</body>
</html>